apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: aglfk2izd-python
  janus-idp.io/tekton: aglfk2izd-python
  backstage.io/kubernetes-id: aglfk2izd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: aglfk2izd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
