apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: aglfk2izd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aglfk2izd-python 
  name: aglfk2izd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: aglfk2izd-python 
